feat: new operators `every` and `some`
tim-smart/strict-callbag-basics pull request #6
Opened 2022-10-18 13:08 UTC by RebeccaStevens

2022-10-22 01:15 UTC, tim-smart commented
Thanks for the contribution!

However, I think I would like to avoid using `toAsyncIterable` in operators, as it adds unnecessary overhead.

There is an internal `subscribe` helper you can use, to make it more callbag-ish. `lastItemFrom` uses it as an example.

2022-10-22 11:10 UTC, RebeccaStevens commented
Updated :)

2022-10-22 17:59 UTC, tim-smart requested changes

2022-10-22 17:59 UTC, tim-smart commented on api/every.ts
> +          result = result && pred(data, index++)
Here you can add a condition guarding a call to `sub.cancel()`.

2022-10-22 17:59 UTC, tim-smart commented on api/some.ts
> +          result = result || pred(data, index++)
If an element passes, then`sub.cancel()`

2022-10-23 23:22 UTC, RebeccaStevens commented
fix submitted

2022-10-23 23:56 UTC, tim-smart commented
Thanks - I just made a quick tweak to fix the failing tests :)

2022-10-23 23:57 UTC, merged

2022-10-24 00:02 UTC, RebeccaStevens commented
Opps, I should have tested before pushing :P